### ISSUE TITLE
release missing sources for tabby.sh

### ISSUE THREAD

**Issue by toxic0berliner** [Eugeny/tabby-web#129]
Hello,
I now seem to understand anything expected at tabby.sh has been more or less abandoned.
I would have liked to revive it somehow, but it seems to me I'm missing a few pieces, I have a tabby web running but don't seem to be able to build the tabby-web-container nom package from anywhere...
Also somehow I can't find any reference to the expected options that the API would provide when querying for gateways... I got the rust API handling the users, I would have liked to get a gateway working before I put in more efforts and it seems anything that was running the tabby.sh/api/1 is nowhere to be found... Maybe @Eugeny could release it even if stating this isn't safe to use and probably without directions on how to set it up... I hope this can be minimal efforts for you and great help for me in building a self-hostable "successor"...

**Comment by Eugeny** [comment]
There are no closed source parts to tabby.sh. The [gateway](https://github.com/Eugeny/tabby-connection-gateway) has external dependencies. Once it's running you simply add it to the tabby-web's database (directly or through `/admin/`) and that's it.

Tabby-web authenticates against the gateway using TLS client auth using the client certificate set via its `CONNECTION_GATEWAY_AUTH_*` Django settings.

**Comment by toxic0berliner** [comment]
Thanks a lot for the confirmation. I will close this then not wanting to have you feel offended or anything wasn't my point 😉
I'll dig deeper then to find out why I'm never getting the tabby-web container to serve the /API
Still need to discover Django and even seems to me you use some kind of overlay or something that isn't helping me find where is the code behind the /api/1/gateway/choose and other /api/1/users and why itns not running in my setup
