### ISSUE TITLE
Unknown message digest

### ISSUE THREAD

**Issue by siccous** [Eugeny/tabby-web#25]
Hello Eugeny,

first I wanna thank you for your amazing project.

I've successfully installed the selfhosted version of Tabby-web in our environment even with the selfhosted version of the gateway. Everything looks great except the last bit with SSH connections. I've tried many of our internal servers (private key, password interactive) and all connections ends with:

![image](https://user-images.githubusercontent.com/7812885/143004969-141f5c36-7635-42c5-a47f-5aa4d80c975d.png)

And honestly I don't know where to look further maybe you can give me some hint what can be wrong with my setup :)

Thanks, Sicco

**Comment by Eugeny** [comment]
Please see if disabling all hashes except `hmac-sha1` in your SSH profile settings -> ciphers helps. If it does, you can try enabling others one by one.

**Comment by siccous** [comment]
Nope, it didn't help at all. Weird thing even when I disable all the ciphers (Ciphers, Key exchange, HMAC, Host key) then it still looks the same.

Dev tools log:

![image](https://user-images.githubusercontent.com/7812885/143285047-87aeec3f-49be-479f-9275-e09b3541f1f0.png)

**Comment by siccous** [comment]
After lot of debugging I've found the issue, it lies here  https://github.com/Eugeny/tabby/blob/77d6a7886f9daddae042ee4bb5028ff742094c31/web/patches/browserify-sign%2B4.2.1.patch

After applying this patch it works as expected, it looks like it's not applied for the tabby-web-container which is published on npm, am I right?

**Comment by Eugeny** [comment]
You're fantastic, I've just fixed it and pushed a nightly release - you can pull it with `./manage.py add_version 1.0.165-nightly.0`
