### ISSUE TITLE
docker-compose 

### ISSUE THREAD

**Issue by sxhoio** [Eugeny/tabby-web#27]
![image](https://user-images.githubusercontent.com/30427262/145237060-d34fb7db-171b-4d20-b573-ee7111f08a6e.png)
I tried to use docker-compose to deploy this service, but I still reported an error when running. I want to know the corresponding versions of docker and compose at runtime. It is still very difficult for me to use

**Comment by sxhoio** [comment]
This is a great project. It would be better if there was multilingual support

**Comment by Eugeny** [comment]
Which Docker and Compose version are you running? I've tested it with:

* Docker version 20.10.10, build b485636
* Docker Compose version v2.1.1

**Comment by sxhoio** [comment]
![image](https://user-images.githubusercontent.com/30427262/145238307-77b55129-626b-4051-ba03-975ff15c1575.png)
This is my environment

**Comment by sxhoio** [comment]
It seems that my version is too low

**Comment by Eugeny** [comment]
Yep, the compose config uses the newer syntax that's available in docker-compose 2.

**Comment by sxhoio** [comment]
SOCIAL_AUTH_GITHUB_Key and social_AUTH_GITHUB_What should secret fill in
![捕获](https://user-images.githubusercontent.com/30427262/145349046-f2b89432-fb3c-4707-9fed-82d2c130460e.PNG)
![image](https://user-images.githubusercontent.com/30427262/145349170-fa4ac227-f51b-4f66-9665-22e7b4026911.png)

**Comment by sxhoio** [comment]
I try to use manual input, but the callback address will report an error

**Comment by sxhoio** [comment]
![image](https://user-images.githubusercontent.com/30427262/145364507-eff207d8-9591-4c1a-9db9-2207655abe80.png)

**Comment by Eugeny** [comment]
`SOCIAL_AUTH_GITHUB_KEY` is the "Client ID", and `SOCIAL_AUTH_GITHUB_SECRET` is the "client secret".

I've totally forgot to add the calllback URLs to the documentation 😳, it should be: `https://<tabby-public-host>/api/1/auth/social/complete/github/`

**Comment by sxhoio** [comment]
I use - e to pass the environment variable, but the client_ Id = none or empty

**Comment by sxhoio** [comment]
docker-compose up -e SOCIAL_AUTH_GITHUB_KEY=xxx -e SOCIAL_AUTH_GITHUB_SECRET=yyy 
    I have replaced the key part, but the ID parameter is not passed when logging in to GitHub

**Comment by Eugeny** [comment]
Sorry, I don't quite get it - where is the client ID empty?

**Comment by sxhoio** [comment]
![无标题](https://user-images.githubusercontent.com/30427262/145709905-c9f1b1a9-51fd-4e66-bfa0-cc3b89cfd57b.png)
I use this command to deploy, but when I verify that GitHub logs in, its API URL parameters are incorrect, and there are some problems with its callback command. Please provide your GitHub OAuth configuration parameters

**Comment by sxhoio** [comment]
My English is very poor. The words are machine translated. There may be problems with some words. If there is something wrong, please be tolerant

**Comment by Eugeny** [comment]
> My English is very poor. 
Don't worry about that. You're saying that github is giving you an error that's somehow related to the callback URL, but I need to see that error to help you.

**Comment by sxhoio** [comment]
![image](https://user-images.githubusercontent.com/30427262/145710392-dc233d12-f71a-4f60-9a1b-1c0546b4511a.png)
The first is his client_ ID is empty when I enter client manually_ After ID, the callback API will report an Error 404
![image](https://user-images.githubusercontent.com/30427262/145710438-71ddf5ae-105c-42c7-98ad-d64e7dfae4ee.png)

**Comment by sxhoio** [comment]
There are some problems with both sending and returning

**Comment by Eugeny** [comment]
Thanks - can you try putting the credentials into the hidden `.env` file in the same folder as `docker-compose.yml` instead?

It should look like this:

```bash
SOCIAL_AUTH_GITHUB_KEY=123...
SOCIAL_AUTH_GITHUB_SECRET=abc...
```

**Comment by sxhoio** [comment]
Thank you very much for your answer. I have successfully deployed it

**Comment by sxhoio** [comment]
This is really a cool project. Come on
![%9E V9QK$)9YW2HD)A00HMW](https://user-images.githubusercontent.com/30427262/145711316-282fbd34-81b6-489e-9086-a2373e9f2a50.png)
![%9E V9QK$)9YW2HD)A00HMW](https://user-images.githubusercontent.com/30427262/145711314-7d0fa788-6f6b-43b0-937c-5d5664028e12.png)

**Comment by Eugeny** [comment]
Thanks! I'm glad you got it working.

**Comment by sxhoio** [comment]
I'm sorry to bother you again. Web app is completely localized, because the network restrictions in our region can't load the login of online web pages

**Comment by sxhoio** [comment]
![image](https://user-images.githubusercontent.com/30427262/145967589-b0ee7bbb-d38b-481f-9c8a-d3257f50800e.png)

**Comment by sxhoio** [comment]
Can the tabby connection gateway be used on Windows clients

**Comment by Eugeny** [comment]
It doesn't require any outside resources if that's what you mean. Do you see any errors in the browser console? The connection gateway can run on Windows too.

**Comment by sxhoio** [comment]
![image](https://user-images.githubusercontent.com/30427262/145972109-ec1502e3-042b-41dd-b74a-c44c2e8efe31.png)
Everything works normally, but nothing is loaded on the main interface

**Comment by Eugeny** [comment]
Please check the "console" tab.

**Comment by sxhoio** [comment]
![image](https://user-images.githubusercontent.com/30427262/145991322-d896aba3-62bd-48ab-9228-bc0e44237d00.png)

**Comment by sxhoio** [comment]
~~~~~
