### ISSUE TITLE
MySQL Database

### ISSUE THREAD

**Issue by capriciousduck** [Eugeny/tabby-web#29]
How much database storage is recommended? I am searching for a free cloud based MySQL database.

**Comment by Eugeny** [comment]
You can use the smallest available size, the database only stores user accounts and config files.

**Comment by capriciousduck** [comment]
Is 5MB good? And what about the SSH servers I connect to? Where will those be stored?

**Comment by Eugeny** [comment]
Well an empty MySQL database is probably larger than that. Host list is a part of the config.

**Comment by capriciousduck** [comment]
I didn't understand, sorry. Do you mean 5 megabytes is not enough?

**Comment by capriciousduck** [comment]
And why am I getting psycopg2 not available error when using PostGreSQL?

**Comment by capriciousduck** [comment]
And should I host gateway service as well?
