### ISSUE TITLE
psycopg2 error

### ISSUE THREAD

**Issue by capriciousduck** [Eugeny/tabby-web#34]
Getting No module found psycopg2 error when using PostgreSQL database.

**Comment by Eugeny** [comment]
Not related to a terminal.

**Comment by capriciousduck** [comment]
Perhaps, I didn't mention my issue correctly. Here is the actual error.

`File "/venv/tabby-web-9TtSrW0h-py3.7/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 29, 
raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
`

**Comment by Eugeny** [comment]
Oh sorry! The docker image ships with the MySQL connector by default, you can rebuild it with `EXTRA_DEPS=psycopg2` to include `psycopg2`

**Comment by capriciousduck** [comment]
Oh. Okay. And regarding database size, would 1GB of storage be enough for PostgreSQL? I'm a noob when it comes to DB's.

**Comment by Eugeny** [comment]
Yes, definitely, it just needs to store your accounts and config files.

**Comment by capriciousduck** [comment]
Thanks!!

**Comment by capriciousduck** [comment]
Hi @Eugeny 

In alpine pyscopg2 is not available via pip, not until postgresql-dev is installed. So,  I googled a bit and found out that **psycopg2-binary** works.  

Just letting you know...

**Comment by Eugeny** [comment]
thanks!
