### ISSUE TITLE
Web-Version not working

### ISSUE THREAD

**Issue by b-bittner** [Eugeny/tabby-web#46]
Hi,
I wanted to try tabby-web on the test-page [https://tabby.sh/app](https://tabby.sh/app) , but it's not working.
Tested  with Chrome and Firefox, on Linux and Windows - but there are just a lot of errors in the browsers dev-console.

**Comment by TheBossAtGames1** [comment]
Web version isn't working for me either

**Comment by Eugeny** [comment]
It's been fixed since.
