### ISSUE TITLE
Can't understand how to generate/connect with Oauth

### ISSUE THREAD

**Issue by lolomin** [Eugeny/tabby-web#50]
Hi,

Just installed and run with docker-compose but can't understand how to log-in :

> Through Github I have a 404 page on github :
https://github.com/login/oauth/authorize?client_id=None&redirect_uri=http://my_own_url.domain.tld/api/1/auth/social/complete/github/&state=Cm9I0zPfzUpjjGZZlXeWLcFiKXAx1G4e&response_type=code&scope=read:user,user:email

so how/where to get these please ? :
-e SOCIAL_AUTH_GITHUB_KEY=xxx -e SOCIAL_AUTH_GITHUB_SECRET=yyy

> Through Microsoft : 

I have a message telling : 
AADSTS700016: Application with identifier 'None' was not found in the directory 'my_company'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

> Through Google I have :
Erreur d'autorisation
Erreur 401 : invalid_client
The OAuth client was not found.

Thanks for help !

Regards,

Laurent

**Comment by Eugeny** [comment]
You need to register your instance as an OAuth app here: https://github.com/settings/applications/new and generate an OAuth secret which you can then pass via the environment variable.

GitHub will ask you for a `Callback URL`, which is `https://<your-host>/api/1/auth/social/complete/github/`

**Comment by lolomin** [comment]
> You need to register your instance as an OAuth app here: https://github.com/settings/applications/new and generate an OAuth secret which you can then pass via the environment variable.
> 
> GitHub will ask you for a `Callback URL`, which is `https://<your-host>/api/1/auth/social/complete/github/`

Thks for answer, generated secret and took the Client ID for the SOCIAL_AUTH_GITHUB_KEY but when trying to log in still the same 404 page returned by github at this address :  
https://github.com/login/oauth/authorize?client_id=None&redirect_uri=http://<myhost.domain.tld>/api/1/auth/social/complete/github/&state=ze8bOZWjsWW62m2KBQdkGj3kxNJ3g9lk&response_type=code&scope=read:user,user:email

Did I miss something ?

Thks !

**Comment by lolomin** [comment]
now having :
AuthFailed at /api/1/auth/social/complete/github/
Authentication failed: The redirect_uri MUST match the registered callback URL for this application.

Finally understood that I needed to made the Callback URL to HTTP rather than HTTPS, don't understand why but everything seems to be OK for now, thks for help :)

**Comment by Eugeny** [comment]
:+1: glad you've figured it out

**Comment by lolomin** [comment]
Hi,

Sorry but coming back to this after a few months, now to simply add a new tabby instance on a new PC and unable to connect back to my own hosted tabby-web instance with github :

Alway having the error :

Django Version: | 3.2.11
-- | --
AuthFailed
Authentication failed: The redirect_uri MUST match the registered callback URL for this application.

It seems the problem is still with the HTTP/HTTPS, I don't know why the callback_url seems to be build with HTTP instead of HTTPS ...

IMHO, this project lacks of documentation to properly lead the user to the good way of authenticating with callback urls and github, google ...

Tried with Github : unable to connect back to my current instance and so unable to recover my saved configs ... How to get access back to my configs please ?
Tried with Google Oauth2 : very complicated ... got a 400 error with redirect_uri_mismatch error also : HTTP can't be used with Google

Why not used an internal local authentication process rather than using a very complicated process with external providers, further more with a self hosted application ?

Regards,

Laurent

**Comment by aogg** [comment]
+1

**Comment by slipperstree** [comment]
BTW, if you use google oauth2, redirect url should be
.../api/1/auth/social/complete/google-oauth2/

**Comment by Sorkai** [comment]
+1

**Comment by Curtion** [comment]
If NGINX reverse proxy is used, adding the `X-Forwarded-Proto` header can solve this issue
