### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by rinqtmith** [Eugeny/tabby-web#60]
Hello,
I am trying to connect tabby.sh via google login. However it returns "Server Error (500)".

F

**Comment by Eugeny** [comment]
You should see the error traceback in the container's stderr.

**Comment by rinqtmith** [comment]
I am connecting via "https://app.tabby.sh/" using Chrome Version 101.0.4951.67 (Official Build) (64-bit).
Only GET error on console.

**Comment by Eugeny** [comment]
Oh sorry - it was an issue due to me migrating to Firebase. Should be fixed now.
