### ISSUE TITLE
Gateways api forbidden error

### ISSUE THREAD

**Issue by rinqtmith** [Eugeny/tabby-web#61]
Hello,

Using "https://app.tabby.sh/" and when I try to ssh to a connection, I see below error.

`Http failure response for https://api.tabby.sh/api/1/gateways/choose: 403`

I am not sure if it is "yabby-connection-gateway" issue or not. If so, please close the issue.

Thank you.

F

**Comment by Eugeny** [comment]
Should be the same as #60, which I've fixed about an hour ago - could you please try logging out and back in again?

**Comment by rinqtmith** [comment]
Cleared cookies and tried again. But still same error.

**Comment by rinqtmith** [comment]
API response is below if it helps.

```
https://api.tabby.sh/api/1/gateways/choose

{
"detail": "Method "GET" not allowed."
}
```

**Comment by KhaaL** [comment]
I'm also having this issue, however I can connect over SSH just fine once I've cleared my cookies. But, if I login with my google account, I also get the error "Http failure response for https://api.tabby.sh/api/1/gateways/choose: 403"

**Comment by rinqtmith** [comment]
Maybe these help:

![image](https://user-images.githubusercontent.com/46543046/176135819-fe11e295-21ae-40d7-b927-9e2f1b4c98a9.png)
![image](https://user-images.githubusercontent.com/46543046/176135876-f05666bb-72d1-411e-adf9-348885773eeb.png)
![image](https://user-images.githubusercontent.com/46543046/176136060-f73b077b-ce71-4e6e-863c-d4903cd95dcb.png)

**Comment by Eugeny** [comment]
This has been fixed by now.
