### ISSUE TITLE
Nothing but a sidebar

### ISSUE THREAD

**Issue by VermiumSifell** [Eugeny/tabby-web#66]
![image](https://user-images.githubusercontent.com/47034338/179361229-2696d534-ed8d-4601-b924-996f2755ad51.png)

I can use sync host and that stuff but just black on the main page

**Comment by THLIVSQAZ** [comment]
same

**Comment by masterwishx** [comment]
do you using docker
i ahve this on docker of hegedussz/tabby-web

**Comment by TheBossAtGames1** [comment]
same

**Comment by xiaoyv404** [comment]
same

**Comment by aeroclown** [comment]
Hi Folks,

So after looking around at this for a while and playing with things. I saw in the developer console that the function to find the current app version was undefined. The instructions don't tell you this explicitly but it seems like the container initialization scripts is not installing a version of the app even though it looks like its supposed to be pulled during the build. If you have nothing but a side bar try running the Add command. Mine went from just a side bar to a working app.

`docker compose run tabby /manage.sh add_version 1.0.163`

**Comment by xiaoyv404** [comment]
> Hi Folks,
> 
> So after looking around at this for a while and playing with things. I saw in the developer console that the function to find the current app version was undefined. The instructions don't tell you this explicitly but it seems like the container initialization scripts is not installing a version of the app even though it looks like its supposed to be pulled during the build. If you have nothing but a side bar try running the Add command. Mine went from just a side bar to a working app.
> 
> `docker compose run tabby /manage.sh add_version 1.0.163`

it works!

**Comment by aeroclown** [comment]
I've discovered there are some issues with 1.0.163 when trying to connect to your own gateway. I recommend running 
`docker compose run tabby /manage.sh add_version 1.0.171-nightly.3` and switching to that release.

I've also found some issues with the documentation for tabby-connection-gateway. However for anyone interested in using it and reverse proxying through caddy. I'll share my docker compose file and caddy config. I'm using a self signed cert and bind mounting the key/cert in the container. Also the --key parameter is not correct, it's --private-key.

**docker-compose.yml**

> services:
>     tabby-gw:
>         image: 'ghcr.io/eugeny/tabby-connection-gateway:latest'
>         restart: always
>         ports:
>         - 9000:9000
>         environment:
>         - PORT=9000
>         - TABBY_AUTH_TOKEN=CEUH0d1Mbc2jvWR3GWOJDPyb9zWzPfL1
>         volumes:
>         - /home/tabby-gw-data/domain.key:/app/ssl.key
>         - /home/tabby-gw-data/domain.pem:/app/ssl.pem
>         command: '--token-auth --host 0.0.0.0 --private-key /app/ssl.key --certificate /app/ssl.pem'

**Caddyfile Format**

> tabby-gw.example.com:443 {
>         encode gzip
>         log {
>                 output file /var/log/caddy/tabby-gw.log
>                 format transform "{common_log}"
>         }
>         reverse_proxy * gw1.example.com:9000 {
>                 header_up Host {host}
>                 header_up X-Real-IP {remote_host}
>                 transport http {
>                         tls
>                         tls_insecure_skip_verify
>                 }
>         }
> }

**Comment by VermiumSifell** [comment]
This seems odd that it is not fixed by the code owner yet. I feel unsecure using this due to this bug which makes me think if there are bugs that is threatening the security of my servers SSH credentials. Would you mind to fix this @Eugeny since this makes atleast me a bit uncomfortable using the application :)
