### ISSUE TITLE
homepage embed of app.tabby.sh fails because of deprecated X-Frame-Options header

### ISSUE THREAD

**Issue by tennox** [Eugeny/tabby-web#74]
```
Invalid X-Frame-Options header was found when loading “https://app.tabby.sh/demo”: “ALLOW-FROM https://tabby.sh/” is not a valid directive.

The loading of “https://app.tabby.sh/terminal” in a frame is denied by “X-Frame-Options“ directive set to “SAMEORIGIN“
```

Looking at [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#directives):

> **ALLOW-FROM=url Deprecated**
>     This is an obsolete directive that no longer works in modern browsers. (Using it will give the same behavior as omitting the header.) Don't use it. The [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) HTTP header has a [frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) directive which you can use instead.

**Comment by Eugeny** [comment]
Fixed, thanks!
