### ISSUE TITLE
docker image not building

### ISSUE THREAD

**Issue by mason-xx** [Eugeny/tabby-web#82]
Stumbled upon this and would love to give it a try. But my docker image won't build. Looks like a python issue ...
Anyone successfully build this lately?

Docker version 20.10.21, build baeda1f
Docker Compose version v2.12.2

`#0 29.47       build/temp.linux-x86_64-cpython-37/_openssl.c: In function '_cffi_d_EVP_PKEY_CTX_set0_rsa_oaep_label':
#0 29.47       build/temp.linux-x86_64-cpython-37/_openssl.c:22582:1: warning: control reaches end of non-void function [-Wreturn-type]
#0 29.47       22582 | }
#0 29.47             | ^
#0 29.47       error: command '/usr/bin/gcc' failed with exit code 1
#0 29.47       [end of output]
#0 29.47
#0 29.47   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 29.47   ERROR: Failed building wheel for cryptography
#0 29.47 Failed to build cryptography
#0 29.47 ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
#0 29.48 WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
#0 29.48 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

failed to solve: executor failed running [/bin/sh -c pip install -U setuptools 'cryptography>=3.0,<3.1' poetry==1.1.7]: exit code: 1
`

**Comment by stinuz** [comment]
I have the same issue. Any solution for this?
